### ISSUE TITLE
Dependencies doesn't really work in Stata

### ISSUE THREAD

**Issue by kbjarkefur** [mizuhirosuzuki/stata-linter#12]
https://github.com/mizuhirosuzuki/stata-linter/blob/06525640f76245b605223bf619c93fb82d35b218/src/stata_linter_detect.ado#L5

https://github.com/mizuhirosuzuki/stata-linter/blob/06525640f76245b605223bf619c93fb82d35b218/src/stata_linter_detect_all.ado#L5

https://github.com/mizuhirosuzuki/stata-linter/blob/06525640f76245b605223bf619c93fb82d35b218/src/stata_linter_detect_all.ado#L38

It seems like you are trying to create dependencies, but there is no real support for dependencies in Stata, and a makeshift solutions to emulate that is not best practice.

You could have solved it like this in a ado file dedicated to a specific project, but not in something that is intended for dissemination.

So these ado files should not include any `ssc install ...` and should not depend on other packages to have been installed. If these commands are disseminated in a package file, then they can depend on each other, but that is it.

**Comment by mizuhirosuzuki** [comment]
Thanks! Good to know that, I think there should be some ways to do the same thing without `ssc install ...`. Let me fix this.
