### ISSUE TITLE
Repeated indentation is inconsistent

### ISSUE THREAD

**Issue by bbdaniels** [mizuhirosuzuki/stata-linter#8]
Original:

<img width="660" alt="Screen Shot(173)" src="https://user-images.githubusercontent.com/1459122/102380126-8d67d000-3f95-11eb-96a7-9c998843d01b.png">

Corrected (note inconsistent indentation between 29-32):

<img width="793" alt="Screen Shot(174)" src="https://user-images.githubusercontent.com/1459122/102380148-935db100-3f95-11eb-82f6-1d8388df400f.png">

**Comment by mizuhirosuzuki** [comment]
Actually the original file is wrong. "//" should be "///", otherwise this code won't run (this is my fault, sorry!). Fixing this should solve the problem.

**Comment by bbdaniels** [comment]
That does indeed work. And it is then intentional to have that on the same indentation as 43, as in:

<img width="546" alt="Screen Shot(175)" src="https://user-images.githubusercontent.com/1459122/102381065-c2c0ed80-3f96-11eb-9e51-c8a00900c14f.png">

**Comment by mizuhirosuzuki** [comment]
Yes this is intentional, I think this is more consistent.
